imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bloq_front_config.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    editorial_contents: &editorial_contents_config
        article:
            pretty_name: Artículo
            menu_class: articulos
            image_filters_enabled: ['article_primary', 'article_intext']
#        gallery:
#            pretty_name: Galería
#            menu_class: galerias
    
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        # handler_id:  ~
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        statics_domain: %statics.server.domain%
        editorial_contents: *editorial_contents_config
        relative_images_path: %bloq_multimedia.images.root_dir_rel_path%
        relative_images_url: %multimedia.images.dir.rel_url% 
        multimedia_domain: %multimedia.domain%
        multimedia_domain_path: %multimedia.domain.path%
        twitter_account_name: %social.twitter.account.name%
        disqus_src_domain_prefix: %comments.disqus.src_domain_prefix%
        disqus_editorial_content_id_prefix: %comments.disqus.editorial_content.id_prefix%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: users
        connections:
            users:                
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%users.database_name%"
                user:     "%users.database_user%"
                password: "%users.database_password%"
                charset:  UTF8
            creator:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%creator.database_name%"
                user:     "%creator.database_user%"
                password: "%creator.database_password%"
                charset:  UTF8
            content:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%content.database_name%"
                user:     "%content.database_user%"
                password: "%content.database_password%"
                charset:  UTF8

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        default_entity_manager: users
        entity_managers:
            users:
                connection:     users
                mappings:
                    FOSUserBundle: ~
                    BloqEntitiesBundle:  ~
                naming_strategy: doctrine.orm.naming_strategy.underscore
            creator:
                connection:     creator
                mappings:
                    BloqEditorBundle: ~
                    BloqMultimediaBundle: ~
                    AppBundle:  ~
                naming_strategy: doctrine.orm.naming_strategy.underscore
            content:
                connection:     content
                mappings:
                    BloqEditorBundle: ~
                    BloqMultimediaBundle: ~
                    AppBundle:  ~
                naming_strategy: doctrine.orm.naming_strategy.underscore

        auto_generate_proxy_classes: "%kernel.debug%"
        resolve_target_entities:
            Bloq\Common\EditorBundle\Entity\EditorialContentInterface: %bloq_editor.editorial_content.article.model_class%
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: %bloq_entities.user.class%
    model_manager_name: users
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: entities.user.manager

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    base_url: / #%statics.server.domain%/
    language: %locale%
    tinymce_buttons:
        stfalcon: # Id of the first button
           title: "Stfalcon"
           image: "http://stfalcon.com/favicon.ico"
    theme:
        simple:
            theme: "advanced" #"modern"
            menubar: false
            toolbar1: "bold italic | styleselect | alignleft aligncenter alignright alignjustify | undo redo | link unlink"
            #toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | hello_world"
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
                
        #advanced:
        #    plugins:
        #        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        #        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        #        - "insertdatetime media nonbreaking save table contextmenu directionality"
        #        - "emoticons template paste textcolor"
        #    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        #    toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
        #    image_advtab: true
        #    templates:
        #        - {title: 'Test template 1', content: 'Test 1'}
        #        - {title: 'Test template 2', content: 'Test 2'}
        #bbcode:
        #    plugins: ["bbcode, code, link, preview"]
        #    menubar: false
        #    toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %front.domain.path%
                cache_prefix: %multimedia.cache_dir.prefix%

    filter_sets:
        article_primary:
            quality: 75
            filters:
                relative_resize: { widen: 640 }
        article_intext:
            quality: 75
            filters:
                relative_resize: { widen: 640 }
        home_carousel_outstandings:
            quality: 75
            filters:
                relative_resize: { widen: 840 }
